### PR TITLE
Changes to PR 47 before merging

### PR DESCRIPTION
**Pull request by cliffordp**
@Stefan2409

I've made quite a few changes and have more to do before this PR is ready... but I wanted to ask if you could make the non-minified output to `.css`/`.js` and the minified output to `.min.css`/`.min.js`

I've already added the PHP enqueuing logic `if SCRIPT_DEBUG` to know which to load.

I found https://github.com/gulpjs/gulp/blob/master/docs/recipes/minified-and-non-minified.md if that might help you.

### CODE REVIEW

**Comment by Stefan2409** [comment]
Yes I can make the minified versions to be *.min.js, *.min.css but github says me you've already merged my changes and so I cannot push to the repository to this feature anymore....hmm or am I wrong?

**Comment by cliffordp** [comment]
Thanks. Invited you as a collaborator just now.

**Comment by cliffordp** [comment]
@Stefan2409 have you used https://github.com/browserslist/browserslist before? Maybe it'd be good to use.

And/Or the https://www.snowpack.dev/ build process

**Comment by cliffordp** [comment]
@Stefan2409 checking if there's anything I can do to help you along

**Comment by cliffordp** [comment]
@Stefan2409 

I created #55 to explore high-level build process improvements so as to not derail the good work done here so far.

This week (if I don't hear back from you before), I'm going to merge these changes as-is so I can continue dev on other things. I'm going to make it so it's not loading unminified files (since they don't yet exist) before merging.

Thanks again for your contributions, past and future!

**Comment by Stefan2409** [comment]
@cliffordp Sorry for my late reply but I'm a bit busy now with my work....

I will look at the minification until the end of this week.

**Pull request merged**
